export const my_recipe = {
  recipe_1: {
    name: 'Kontomire Stew',
    preparation_time: '30-45 minutes',
    How_To_Eat: 'Goes With Rice or Boiled Yam/Plantian',
    ingredients: [
      '1/2 cup rice',
      '15 Kontomire leaves',
      '4-6 small tomatoes',
      '¼ cup turkey berries',
      '3 med onions',
      'pepper',
      '2 med smoked salmon',
      '1 cup melon seeds (akatoa, egusi, agushie)',
      '½ cup palm oil',
      'momoni optional',
      '2 tsp grounded shrimp',
      'salt as required',
    ],
    instructions: [
      'Soak melon seeds in water, set aside. Wash kontomire leaves with a generous amount of salt to prevent itching of hands when cutting.',
      'Cut kontomire into desired stripes. Put the cut kotomire into a saucepan with little water and place on high heat. Cover and bring to a boil.',
      'Turn the kontomire after about five minutes of cooking to make sure everything is cooked through.',
      'Turn off fire and set aside.',
      'Blend two onions, tomatoes, pepper and turkey berries together, set aside.',
      'Remove the flesh of the salmon, break into two and remove the bones, break into desired sizes, set aside.',
      'Wash the soaked melon seeds and put into a blender.', 
      'Add about ¼ teaspoon salt and just enough water to blend into a paste. Set aside.', 
      'Slice the remaining onion.',
      'Pour palm oil into a medium saucepan, add half of the sliced onions and momoni (fermented fish) if using.',
      'Fry till onions are softened.',
      'Add the blended tomatoes, onions, turkey berries and pepper. Bring to a simmer on medium heat.',
      'Add the salmon, salt and grounded shrimp if using. Cover and let simmer for 7 to 10 minutes till sauce is bare thickened.',
      'Add in the blended melon seeds, DO NOT STIR, cover and reduce heat to low.',
      'Let it simmer 8 to 10 minutes or till the blended melon seeds sets.',
      'Gently stir in the steamed kontomire.',
      'Add the remaining sliced onions, let simmer for about five minutes till onions are softened. Serve with yam, rice, cocoyam, cassava, plantains or sweet potatoes.',
    ],
  },
  recipe_2: {
    name: 'Gari Foto',
    preparation_time: '30 minutes',
    ingredients: [
      'Gari',
      'Water',
      'Salt',
      'Powdered pepper',
      'Tomatoes',
      'Onions',
      'Carrot',
      'Green bell pepper',
      'Sardine',
      'Cooking oil',
    ],
    instructions: [
      'Chop your tomatoes, onions, carrot and green pepper onto a plate and set aside.',
      'Pour some cooking oil into a pan on fire.',
      'First put in your onions, then add the tomatoes. Stir and leave it to cook for a while.',
      ' Next, add salt and pepper and stir.',
      ' Add your chopped carrot, green bell pepper and sardine and stir.',
      'Pour gari into a bowl and wet it with a little water.',
      'Add the gari to the sauce on fire and stir till it mixes well.',
      'Your gari foto is ready to serve now.',
    ],
 
  }
};